# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'diary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for diary
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'

  # Required by Google SignIn SDK
  pod 'GoogleSignIn'

  target 'diary-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'diaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'diary-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for diary-tvOS

end
